version: '3.10'

services:
  web:
    container_name: lufemage_app
    
    build: 
      context: .
    restart: always
    tty: true
    volumes:
      - .:/app
    environment:
      - LANG=es_CO.UTF-8
      - DJANGO_ENV=$ENV
    ports:
      - 8000:8000