version: '3.4'

services:
  devopsmoises:
    image: devopsmoises
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000

    depends_on:
      - db 
  db:
    image: postgres:13
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data: